# One external location per zone (bronze, silver, gold, landing)
resource "databricks_external_location" "this" {
  provider        = databricks.workspace
  for_each        = toset(local.zones)
  name            = "${var.prefix}-${each.key}"
  url             = "abfss://${each.key}@${azurerm_storage_account.adls.name}.dfs.core.windows.net/"
  credential_name = databricks_storage_credential.this.name
  force_destroy   = true

  depends_on = [databricks_metastore_assignment.this]
}

resource "databricks_catalog" "this" {
  provider      = databricks.workspace
  for_each      = toset(local.zones)
  name          = each.key
  comment       = "${title(each.key)} catalog"
  storage_root  = "abfss://${each.key}@${azurerm_storage_account.adls.name}.dfs.core.windows.net/"
  force_destroy = true

  depends_on = [databricks_external_location.this]
}

# Default schema for data layers only — landing uses a raw schema backed by external volumes
resource "databricks_schema" "default" {
  provider      = databricks.workspace
  for_each      = toset(local.layers)
  catalog_name  = databricks_catalog.this[each.key].name
  name          = "default"
  force_destroy = true
}


moved {
  from = databricks_external_location.admin
  to   = databricks_external_location.this["admin"]
}

moved {
  from = databricks_catalog.admin
  to   = databricks_catalog.this["admin"]
}

resource "databricks_schema" "admin_shared" {
  provider      = databricks.workspace
  catalog_name  = databricks_catalog.this["admin"].name
  name          = "shared"
  force_destroy = true
}

locals {
  # All zones get account users navigation access.
  # Team SPs get schema-level ALL PRIVILEGES via databricks_grants.team_schema in data-product-teams.tf.
  catalog_grants = { for z in local.zones : z => { account_users = true } }

  _catalog_name = { for k in local.zones : k => databricks_catalog.this[k].name }
}

resource "databricks_grants" "catalog" {
  provider = databricks.workspace
  for_each = local.catalog_grants
  catalog  = local._catalog_name[each.key]

  dynamic "grant" {
    for_each = each.value.account_users ? [1] : []
    content {
      principal  = "account users"
      privileges = ["USE_CATALOG", "USE_SCHEMA"]
    }
  }

  # Team SPs get full ownership of admin so they can deploy and execute shared functions (masking UDFs).
  dynamic "grant" {
    for_each = each.key == "admin" ? var.data_product_teams : {}
    content {
      principal  = databricks_service_principal.teams[grant.key].application_id
      privileges = ["ALL PRIVILEGES", "MANAGE"]
    }
  }

  # SAR app SP needs READ access to bronze to execute upstream bronze queries.
  # Runs as the app's own SP (not the user) so the SP requires explicit grants.
  dynamic "grant" {
    for_each = each.key == "bronze" && var.sar_app_sp_id != "" ? [1] : []
    content {
      principal  = var.sar_app_sp_id
      privileges = ["USE_CATALOG", "USE_SCHEMA", "SELECT"]
    }
  }

  grant {
    principal  = databricks_group.this["data_platform_admins"].display_name
    privileges = ["ALL PRIVILEGES", "MANAGE"]
  }
}

# Governed tag ASSIGN grants are not supported by databricks_grants in the current provider.
# They are applied automatically via the governance DABs job (grant_governed_tags task),
# which runs governance/grant_governed_tags.sql — a file generated by CI from
# terraform output team_sp_application_ids. No manual action required.