-- SAR Article 15 access-report audit trail — owned by the data_platform_admins
-- team (see terraform/data-product-teams.tf + terraform/catalogs.tf
-- databricks_grants.admin_access). Deliberately NOT bronze/silver/gold-scoped
-- so it is exempt from the Auto TTL sweep in governance/apply_auto_ttl.py —
-- this audit trail must be retained, not auto-purged.
--
-- Grants for this schema are Terraform-only and intentionally narrow (the
-- platform team's SP for writes, data stewards for read-only review) — do not
-- add a `GRANT ... TO account users` here the way
-- create_retention_compliance_view.sql does for its dashboard-facing view;
-- this data is not for general account access.
--
-- Same "evidence, never a copy" principle as admin.erasure: this table proves
-- a disclosure happened — which tables, how many rows, which columns were
-- included vs. redacted — without ever storing the disclosed data itself.
-- subject_ref_hash and row_key_hash are always produced via
-- admin.shared.hash_access_subject_ref/hash_access_row_key — never a
-- plaintext identifier, and the generated report document is never persisted
-- here (it exists only as the reviewer's one-time download).

CREATE TABLE IF NOT EXISTS admin.access.requests (
  request_id       STRING    COMMENT 'UUID generated by the app when a reviewer confirms an access report.',
  subject_ref_hash STRING    COMMENT 'admin.shared.hash_access_subject_ref(subject identifier) — never plaintext.',
  requested_by     STRING    COMMENT 'Identity (UPN/email) of the confirming data steward.',
  requested_at     TIMESTAMP,
  status           STRING    COMMENT 'Open string, not an enum — e.g. COMPLETED/PARTIAL/FAILED.',
  completed_at     TIMESTAMP
) COMMENT 'One row per Art.15 access-report case. See admin.access.request_items for the per-table detail.';

CREATE TABLE IF NOT EXISTS admin.access.request_items (
  request_id            STRING        COMMENT 'Foreign key to admin.access.requests.request_id.',
  table_full_name        STRING        COMMENT 'catalog.schema.table the report drew records from.',
  provenance             STRING        COMMENT 'How this table was found: direct / upstream / downstream.',
  matched_column_or_tag  STRING,
  rows_disclosed         INT           COMMENT 'Rows actually included in the generated report.',
  columns_included       ARRAY<STRING> COMMENT 'Column names included in the report for this table.',
  columns_redacted       ARRAY<STRING> COMMENT 'class.*-tagged columns present on the table but excluded from disclosure (e.g. suspected third-party data — see docs/sar-app.md).',
  row_key_hash           ARRAY<STRING> COMMENT 'admin.shared.hash_access_row_key(...) per disclosed row — never plaintext.',
  generated_at           TIMESTAMP
) COMMENT 'One row per (request, source table) included in a generated access report — evidence of exactly what was disclosed, never a copy of the disclosed data itself.';
