-- SAR erasure audit trail — owned by the data_platform_admins team (see
-- terraform/data-product-teams.tf + terraform/catalogs.tf databricks_grants.admin_erasure).
-- Deliberately NOT bronze/silver/gold-scoped so it is exempt from the Auto TTL sweep in
-- governance/apply_auto_ttl.py — this audit trail must be retained, not auto-purged.
--
-- Grants for this schema are Terraform-only and intentionally narrow (the platform
-- team's SP for writes, data stewards for read-only review) — do not add a
-- `GRANT ... TO account users` here the way create_retention_compliance_view.sql does
-- for its dashboard-facing view; this data is not for general account access.
--
-- Per the DPO/GDPR requirements this audit trail was designed against: it is evidence
-- that erasure happened, never a copy of the erased data. subject_ref_hash and
-- row_key_hash are always produced via admin.shared.hash_subject_ref/hash_row_key —
-- never store a plaintext identifier or the literal executed DELETE predicate here.

CREATE TABLE IF NOT EXISTS admin.erasure.requests (
  request_id       STRING    COMMENT 'UUID generated by the app when a reviewer confirms an erasure.',
  subject_ref_hash STRING    COMMENT 'admin.shared.hash_subject_ref(subject identifier) — never plaintext.',
  requested_by     STRING    COMMENT 'Identity (UPN/email) of the confirming data steward.',
  legal_basis      STRING    COMMENT 'Which GDPR Art. 17(1) erasure ground applies.',
  requested_at     TIMESTAMP,
  status           STRING    COMMENT 'Open string, not an enum — e.g. PENDING/COMPLETED/PARTIAL/FAILED. Left open so a future exempt-from-erasure status can be added without a migration.',
  completed_at     TIMESTAMP
) COMMENT 'One row per erasure case. See admin.erasure.request_items for the per-table detail.';

CREATE TABLE IF NOT EXISTS admin.erasure.request_items (
  request_id           STRING        COMMENT 'Foreign key to admin.erasure.requests.request_id.',
  table_full_name       STRING        COMMENT 'catalog.schema.table that was targeted.',
  provenance            STRING        COMMENT 'How this table was found: direct / upstream / downstream.',
  matched_column_or_tag STRING,
  rows_selected         INT           COMMENT 'Rows the reviewer selected in the review UI.',
  rows_deleted          INT           COMMENT 'Rows actually deleted — compared against rows_selected as a sanity check.',
  row_targeting_method  STRING        COMMENT 'primary_key or full_row_equality — see apps/sar_app/erasure.py.',
  row_key_hash          ARRAY<STRING> COMMENT 'admin.shared.hash_row_key(...) per deleted row — never plaintext.',
  vacuum_retention_raw  STRING        COMMENT 'delta.deletedFileRetentionDuration captured at execution time, e.g. "7 days".',
  vacuum_retention_days INT,
  estimated_purge_by    TIMESTAMP     COMMENT 'executed_at + vacuum_retention_days — when the physical files are expected to actually be gone.',
  execution_status      STRING        COMMENT 'Open string — e.g. SUCCEEDED/FAILED/SKIPPED.',
  error_message         STRING,
  executed_at           TIMESTAMP
) COMMENT 'One row per (request, affected table), written immediately after that table''s delete attempt — not batched until the whole request finishes, so a mid-run failure does not lose evidence for tables that already succeeded.';
