"""Lineage traversal and display-table construction.

``LineageClient`` performs iterative BFS over ``system.access.table_lineage``
in both the upstream and downstream directions.  ``_relative_time`` is a
module-private helper used exclusively by ``build_display_table``.
"""

from __future__ import annotations

import pandas as pd

from database import DatabricksClient


def _relative_time(ts) -> str:
    """Convert *ts* to a human-readable relative string (e.g. 'yesterday')."""
    if ts is None or pd.isna(ts):
        return "unknown"
    try:
        now = pd.Timestamp.utcnow()
        ts_utc = (
            pd.Timestamp(ts).tz_convert("UTC")
            if pd.Timestamp(ts).tzinfo is not None
            else pd.Timestamp(ts).tz_localize("UTC")
        )
        days = (now - ts_utc).days
        if days == 0:
            return "today"
        if days == 1:
            return "yesterday"
        if days < 7:
            return f"{days} days ago"
        if days < 14:
            return "last week"
        if days < 30:
            return f"{days // 7} weeks ago"
        if days < 60:
            return "last month"
        return f"{days // 30} months ago"
    except Exception:  # noqa: BLE001
        return str(ts)


class LineageClient:
    """Traverses ``system.access.table_lineage`` for upstream/downstream tables.

    Uses iterative BFS with a visited set to avoid cycles. Drift and profile
    metrics tables (auto-generated by Lakehouse Monitoring) are excluded from
    results and traversal in both directions.
    """

    _EXCLUDE_SUFFIX: str = r"_(drift|profile)_metrics$"
    _LOOKBACK_DAYS: int = 365

    def __init__(self, client: DatabricksClient) -> None:
        self._client = client

    def upstream(
        self,
        source_tables: list[str],
        # Safety cap on BFS depth, not an expected real-world bound — actual
        # pipelines here are 2-4 hops deep. Guards against runaway traversal
        # over pathologically long or cyclic lineage graphs.
        max_depth: int = 20,
    ) -> pd.DataFrame:
        """Return transitive upstream lineage for *source_tables*.

        Columns: ``matched_table, upstream_table, source_catalog,
        entity_type, last_seen, depth``.
        """
        return self._traverse(source_tables, direction="upstream", max_depth=max_depth)

    def downstream(
        self,
        source_tables: list[str],
        max_depth: int = 20,  # see upstream() for rationale
    ) -> pd.DataFrame:
        """Return transitive downstream lineage for *source_tables*.

        Columns: ``matched_table, downstream_table, target_catalog,
        entity_type, last_seen, depth``.
        """
        return self._traverse(source_tables, direction="downstream", max_depth=max_depth)

    def build_display_table(
        self,
        upstream_df: pd.DataFrame,
        downstream_df: pd.DataFrame,
    ) -> pd.DataFrame:
        """Merge upstream/downstream results into a single display table.

        Columns returned: ``Name, Direction, Type, Last activity``.
        Deduplicated on ``(Name, Direction)`` keeping the shortest path;
        most-recent ``last_seen`` breaks ties.
        """
        parts = []

        if not upstream_df.empty:
            up = upstream_df[["upstream_table", "entity_type", "last_seen", "depth"]].copy()
            up = up.rename(columns={"upstream_table": "Name", "entity_type": "Type"})
            up["Direction"] = "↑ Upstream"
            parts.append(up)

        if not downstream_df.empty:
            dn = downstream_df[
                ["downstream_table", "entity_type", "last_seen", "depth"]
            ].copy()
            dn = dn.rename(columns={"downstream_table": "Name", "entity_type": "Type"})
            dn["Direction"] = "↓ Downstream"
            parts.append(dn)

        if not parts:
            return pd.DataFrame()

        combined = pd.concat(parts, ignore_index=True)
        combined["Last activity"] = combined["last_seen"].apply(_relative_time)
        combined = combined.sort_values(["depth", "last_seen"], ascending=[True, False])
        combined = combined.drop_duplicates(subset=["Name", "Direction"], keep="first")
        combined = combined.sort_values(["depth", "Direction"], ascending=[True, True])
        return combined[["Name", "Direction", "Type", "Last activity"]].reset_index(drop=True)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _traverse(
        self,
        source_tables: list[str],
        direction: str,
        max_depth: int,
    ) -> pd.DataFrame:
        if not source_tables:
            return pd.DataFrame()

        all_rows: list[pd.DataFrame] = []
        frontier = list(source_tables)
        visited: set[str] = set(source_tables)
        depth = 1

        while frontier and depth <= max_depth:
            in_list = ", ".join(f"'{t}'" for t in frontier)
            df = self._client.query(self._build_lineage_sql(in_list, direction))
            if df.empty:
                break

            df["depth"] = depth
            all_rows.append(df)

            next_col = "upstream_table" if direction == "upstream" else "downstream_table"
            new = set(df[next_col].tolist()) - visited
            visited.update(new)
            frontier = list(new)
            depth += 1

        return pd.concat(all_rows, ignore_index=True) if all_rows else pd.DataFrame()

    def _build_lineage_sql(self, in_list: str, direction: str) -> str:
        base = f"""
            SELECT
                {{filter_col}}                       AS matched_table,
                {{result_col}}                       AS {{result_alias}},
                {{catalog_col}}                      AS {{catalog_alias}},
                COALESCE(entity_type, 'unknown')     AS entity_type,
                MAX(event_time)                      AS last_seen
            FROM system.access.table_lineage
            WHERE {{filter_col}} IN ({in_list})
              AND {{result_col}} IS NOT NULL
              AND {{result_col}} NOT RLIKE '{self._EXCLUDE_SUFFIX}'
              AND event_date >= current_date() - {self._LOOKBACK_DAYS}
            GROUP BY ALL
            ORDER BY last_seen DESC
        """
        if direction == "upstream":
            return base.format(
                filter_col="target_table_full_name",
                result_col="source_table_full_name",
                result_alias="upstream_table",
                catalog_col="source_table_catalog",
                catalog_alias="source_catalog",
            )
        return base.format(
            filter_col="source_table_full_name",
            result_col="target_table_full_name",
            result_alias="downstream_table",
            catalog_col="target_table_catalog",
            catalog_alias="target_catalog",
        )
