"""Lineage traversal and display-table construction.

``LineageClient`` performs iterative BFS over ``system.access.table_lineage``
in both the upstream and downstream directions.  ``_relative_time`` is a
module-private helper used exclusively by ``build_display_table``.
"""

from __future__ import annotations

import pandas as pd

from database import DatabricksClient


def _relative_time(ts) -> str:
    """Convert *ts* to a human-readable relative string (e.g. 'yesterday')."""
    if ts is None or pd.isna(ts):
        return "unknown"
    try:
        now = pd.Timestamp.utcnow()
        ts_utc = (
            pd.Timestamp(ts).tz_convert("UTC")
            if pd.Timestamp(ts).tzinfo is not None
            else pd.Timestamp(ts).tz_localize("UTC")
        )
        days = (now - ts_utc).days
        if days == 0:
            return "today"
        if days == 1:
            return "yesterday"
        if days < 7:
            return f"{days} days ago"
        if days < 14:
            return "last week"
        if days < 30:
            return f"{days // 7} weeks ago"
        if days < 60:
            return "last month"
        return f"{days // 30} months ago"
    except Exception:  # noqa: BLE001
        return str(ts)


def _is_table_full_name(name: object) -> bool:
    """Return True if *name* looks like a ``catalog.schema.table`` name.

    ``system.access.column_lineage`` can point at non-table entities
    (dashboards, notebook variables, temp views) where the full-name column
    is ``NULL`` or lacks the usual three dot-separated parts.
    """
    return name is not None and str(name).count(".") == 2


class LineageClient:
    """Traverses ``system.access.table_lineage`` for upstream/downstream tables.

    Uses iterative BFS with a visited set to avoid cycles. Drift and profile
    metrics tables (auto-generated by Lakehouse Monitoring) are excluded from
    results and traversal in both directions.
    """

    _EXCLUDE_SUFFIX: str = r"_(drift|profile)_metrics$"
    _LOOKBACK_DAYS: int = 365

    def __init__(self, client: DatabricksClient) -> None:
        self._client = client

    def upstream(
        self,
        source_tables: list[str],
        # Safety cap on BFS depth, not an expected real-world bound — actual
        # pipelines here are 2-4 hops deep. Guards against runaway traversal
        # over pathologically long or cyclic lineage graphs.
        max_depth: int = 20,
    ) -> pd.DataFrame:
        """Return transitive upstream lineage for *source_tables*.

        Columns: ``matched_table, upstream_table, source_catalog,
        entity_type, last_seen, depth``.
        """
        return self._traverse(source_tables, direction="upstream", max_depth=max_depth)

    def downstream(
        self,
        source_tables: list[str],
        max_depth: int = 20,  # see upstream() for rationale
    ) -> pd.DataFrame:
        """Return transitive downstream lineage for *source_tables*.

        Columns: ``matched_table, downstream_table, target_catalog,
        entity_type, last_seen, depth``.
        """
        return self._traverse(source_tables, direction="downstream", max_depth=max_depth)

    def column_lineage_to_bronze(
        self,
        initial_conditions: dict[str, list[tuple[str, str, str]]],
        max_depth: int = 10,
    ) -> pd.DataFrame:
        """Trace column lineage upstream until reaching bronze tables.

        Performs a BFS over ``system.access.column_lineage``, accumulating
        columns that land in the bronze catalog. Carries the original tag and
        clean search value through intermediate hops (e.g. gold → silver →
        bronze), so callers can build search conditions without knowing the
        intermediate path.

        Args:
            initial_conditions: Maps each matched silver/gold table full name
                to a list of ``(column_name, tag, clean_val)`` tuples.
            max_depth: Safety cap on BFS iterations.

        Returns:
            DataFrame with columns ``source_table_full_name``,
            ``source_column_name``, ``tag``, ``clean_val``. Empty if no
            bronze lineage found.
        """
        if not initial_conditions:
            return pd.DataFrame()

        # frontier: (table_full_name, column_name) -> (tag, clean_val)
        frontier: dict[tuple[str, str], tuple[str, str]] = {
            (table, col): (tag, clean_val)
            for table, cols_info in initial_conditions.items()
            for col, tag, clean_val in cols_info
        }
        visited: set[tuple[str, str]] = set(frontier)
        bronze_rows: list[dict[str, str]] = []

        for _ in range(max_depth):
            if not frontier:
                break

            table_to_cols: dict[str, set[str]] = {}
            for table, col in frontier:
                table_to_cols.setdefault(table, set()).add(col)

            table_in = ", ".join(f"'{t}'" for t in table_to_cols)
            col_in = ", ".join(
                f"'{c}'" for c in {c for cols in table_to_cols.values() for c in cols}
            )

            df = self._client.query(f"""
                SELECT source_table_full_name,
                       source_column_name,
                       target_table_full_name,
                       target_column_name
                FROM   system.access.column_lineage
                WHERE  target_table_full_name IN ({table_in})
                  AND  target_column_name     IN ({col_in})
                  AND  source_table_full_name IS NOT NULL
                  AND  event_date             >= current_date() - {self._LOOKBACK_DAYS}
                GROUP BY ALL
            """)

            if df.empty:
                break

            next_frontier: dict[tuple[str, str], tuple[str, str]] = {}

            for _, row in df.iterrows():
                tgt_key = (row.target_table_full_name, row.target_column_name)
                if tgt_key not in frontier:
                    continue  # cross-table false match from independent IN predicates

                if not _is_table_full_name(row.source_table_full_name):
                    continue

                tag, clean_val = frontier[tgt_key]
                src_key = (row.source_table_full_name, row.source_column_name)

                if src_key in visited:
                    continue
                visited.add(src_key)

                if str(row.source_table_full_name).startswith("bronze."):
                    bronze_rows.append({
                        "source_table_full_name": row.source_table_full_name,
                        "source_column_name":     row.source_column_name,
                        "tag":                    tag,
                        "clean_val":              clean_val,
                    })
                else:
                    next_frontier[src_key] = (tag, clean_val)

            frontier = next_frontier

        if not bronze_rows:
            return pd.DataFrame()
        return pd.DataFrame(bronze_rows)

    def column_lineage_downstream(
        self,
        initial_conditions: dict[str, list[tuple[str, str, str]]],
        max_depth: int = 10,
    ) -> pd.DataFrame:
        """Trace column lineage downstream from matched tables.

        Performs a BFS over ``system.access.column_lineage`` in the forward
        direction. Unlike ``column_lineage_to_bronze`` (which only collects
        terminal bronze columns), every hop is collected here: a SAR-relevant
        copy of a subject's data may exist in any derived table, not only at
        a fixed terminal layer, and downstream copies often don't inherit the
        originating ``class.*`` tag. Carries the original tag and clean
        search value through intermediate hops so callers can build search
        conditions without knowing the derived table's schema.

        Args:
            initial_conditions: Maps each matched silver/gold table full name
                to a list of ``(column_name, tag, clean_val)`` tuples.
            max_depth: Safety cap on BFS iterations.

        Returns:
            DataFrame with columns ``target_table_full_name``,
            ``target_column_name``, ``tag``, ``clean_val``. Empty if no
            downstream lineage found.
        """
        if not initial_conditions:
            return pd.DataFrame()

        # frontier: (table_full_name, column_name) -> (tag, clean_val)
        frontier: dict[tuple[str, str], tuple[str, str]] = {
            (table, col): (tag, clean_val)
            for table, cols_info in initial_conditions.items()
            for col, tag, clean_val in cols_info
        }
        visited: set[tuple[str, str]] = set(frontier)
        downstream_rows: list[dict[str, str]] = []

        for _ in range(max_depth):
            if not frontier:
                break

            table_to_cols: dict[str, set[str]] = {}
            for table, col in frontier:
                table_to_cols.setdefault(table, set()).add(col)

            table_in = ", ".join(f"'{t}'" for t in table_to_cols)
            col_in = ", ".join(
                f"'{c}'" for c in {c for cols in table_to_cols.values() for c in cols}
            )

            df = self._client.query(f"""
                SELECT source_table_full_name,
                       source_column_name,
                       target_table_full_name,
                       target_column_name
                FROM   system.access.column_lineage
                WHERE  source_table_full_name IN ({table_in})
                  AND  source_column_name     IN ({col_in})
                  AND  target_table_full_name IS NOT NULL
                  AND  event_date             >= current_date() - {self._LOOKBACK_DAYS}
                GROUP BY ALL
            """)

            if df.empty:
                break

            next_frontier: dict[tuple[str, str], tuple[str, str]] = {}

            for _, row in df.iterrows():
                src_key = (row.source_table_full_name, row.source_column_name)
                if src_key not in frontier:
                    continue  # cross-table false match from independent IN predicates

                if not _is_table_full_name(row.target_table_full_name):
                    continue

                tag, clean_val = frontier[src_key]
                tgt_key = (row.target_table_full_name, row.target_column_name)

                if tgt_key in visited:
                    continue
                visited.add(tgt_key)

                downstream_rows.append({
                    "target_table_full_name": row.target_table_full_name,
                    "target_column_name":     row.target_column_name,
                    "tag":                    tag,
                    "clean_val":              clean_val,
                })
                next_frontier[tgt_key] = (tag, clean_val)

            frontier = next_frontier

        if not downstream_rows:
            return pd.DataFrame()
        return pd.DataFrame(downstream_rows)

    def build_graphviz(
        self,
        matched_full_names: list[str],
        upstream_df: pd.DataFrame,
        downstream_df: pd.DataFrame,
        bronze_tables: set[str],
        downstream_copy_tables: set[str],
    ) -> str:
        """Build a Graphviz DOT graph of the lineage traversal for display.

        Tables reached only by the generic ``table_lineage`` BFS (no actual
        PII match) are dashed/grey. Tables with an actual match are solid,
        colored by how they were found: direct tag match (blue), upstream
        bronze source via column lineage (violet), downstream copy via
        column lineage (teal).
        """
        nodes: dict[str, str] = {}
        edges: list[tuple[str, str]] = []

        for name in matched_full_names:
            nodes[name] = 'style=filled,fillcolor="#5b8def",fontcolor=white'

        if not upstream_df.empty:
            for _, row in upstream_df.iterrows():
                nodes.setdefault(row.upstream_table, 'style=dashed,color="#888888"')
                edges.append((row.upstream_table, row.matched_table))

        if not downstream_df.empty:
            for _, row in downstream_df.iterrows():
                nodes.setdefault(row.downstream_table, 'style=dashed,color="#888888"')
                edges.append((row.matched_table, row.downstream_table))

        for name in bronze_tables:
            nodes[name] = 'style=filled,fillcolor="#9b6bff",fontcolor=white'

        for name in downstream_copy_tables:
            nodes[name] = 'style=filled,fillcolor="#2dd4bf",fontcolor=black'

        def esc(name: str) -> str:
            return name.replace('"', '\\"')

        lines = ["digraph lineage {", "rankdir=LR;", 'node [shape=box,fontname="Helvetica"];']
        for name, style in nodes.items():
            lines.append(f'"{esc(name)}" [{style}];')
        for src, tgt in edges:
            lines.append(f'"{esc(src)}" -> "{esc(tgt)}";')
        lines.append("}")
        return "\n".join(lines)

    def build_display_table(
        self,
        upstream_df: pd.DataFrame,
        downstream_df: pd.DataFrame,
    ) -> pd.DataFrame:
        """Merge upstream/downstream results into a single display table.

        Columns returned: ``Name, Direction, Type, Last activity``.
        Deduplicated on ``(Name, Direction)`` keeping the shortest path;
        most-recent ``last_seen`` breaks ties.
        """
        parts = []

        if not upstream_df.empty:
            up = upstream_df[["upstream_table", "entity_type", "last_seen", "depth"]].copy()
            up = up.rename(columns={"upstream_table": "Name", "entity_type": "Type"})
            up["Direction"] = "↑ Upstream"
            parts.append(up)

        if not downstream_df.empty:
            dn = downstream_df[
                ["downstream_table", "entity_type", "last_seen", "depth"]
            ].copy()
            dn = dn.rename(columns={"downstream_table": "Name", "entity_type": "Type"})
            dn["Direction"] = "↓ Downstream"
            parts.append(dn)

        if not parts:
            return pd.DataFrame()

        combined = pd.concat(parts, ignore_index=True)
        combined["Last activity"] = combined["last_seen"].apply(_relative_time)
        combined = combined.sort_values(["depth", "last_seen"], ascending=[True, False])
        combined = combined.drop_duplicates(subset=["Name", "Direction"], keep="first")
        combined = combined.sort_values(["depth", "Direction"], ascending=[True, True])
        return combined[["Name", "Direction", "Type", "Last activity"]].reset_index(drop=True)

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _traverse(
        self,
        source_tables: list[str],
        direction: str,
        max_depth: int,
    ) -> pd.DataFrame:
        if not source_tables:
            return pd.DataFrame()

        all_rows: list[pd.DataFrame] = []
        frontier = list(source_tables)
        visited: set[str] = set(source_tables)
        depth = 1

        while frontier and depth <= max_depth:
            in_list = ", ".join(f"'{t}'" for t in frontier)
            df = self._client.query(self._build_lineage_sql(in_list, direction))
            if df.empty:
                break

            df["depth"] = depth
            all_rows.append(df)

            next_col = "upstream_table" if direction == "upstream" else "downstream_table"
            new = set(df[next_col].tolist()) - visited
            visited.update(new)
            frontier = list(new)
            depth += 1

        return pd.concat(all_rows, ignore_index=True) if all_rows else pd.DataFrame()

    def _build_lineage_sql(self, in_list: str, direction: str) -> str:
        base = f"""
            SELECT
                {{filter_col}}                       AS matched_table,
                {{result_col}}                       AS {{result_alias}},
                {{catalog_col}}                      AS {{catalog_alias}},
                COALESCE(entity_type, 'unknown')     AS entity_type,
                MAX(event_time)                      AS last_seen
            FROM system.access.table_lineage
            WHERE {{filter_col}} IN ({in_list})
              AND {{result_col}} IS NOT NULL
              AND {{result_col}} NOT RLIKE '{self._EXCLUDE_SUFFIX}'
              AND event_date >= current_date() - {self._LOOKBACK_DAYS}
            GROUP BY ALL
            ORDER BY last_seen DESC
        """
        if direction == "upstream":
            return base.format(
                filter_col="target_table_full_name",
                result_col="source_table_full_name",
                result_alias="upstream_table",
                catalog_col="source_table_catalog",
                catalog_alias="source_catalog",
            )
        return base.format(
            filter_col="source_table_full_name",
            result_col="target_table_full_name",
            result_alias="downstream_table",
            catalog_col="target_table_catalog",
            catalog_alias="target_catalog",
        )
